"use client";

import { useEffect, useMemo, useState } from "react";
import type { Candle } from "@/lib/types";

type Token = { symbol: string; name: string; code: string; price: number; change: number };
type Asset = { coin: string; free: number; locked: number; total: number };
const currency = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 });
const intervals = ["1m", "5m", "15m", "1h", "4h", "1d"];

function Candles({ candles }: { candles: Candle[] }) {
  const bounds = useMemo(() => ({ low: Math.min(...candles.map(c => c.low)), high: Math.max(...candles.map(c => c.high)) }), [candles]);
  if (!candles.length) return <div className="chart-empty">Loading market data…</div>;
  const h = 340, w = 900, pad = 18, span = bounds.high - bounds.low || 1, x = (i: number) => pad + i * (w - pad * 2) / candles.length, y = (v: number) => pad + (bounds.high - v) / span * (h - pad * 2), body = Math.max(3, (w - pad * 2) / candles.length * .58);
  return <svg className="candles" viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Interactive candlestick chart">{[.2,.4,.6,.8].map(n => <line key={n} x1={pad} x2={w-pad} y1={h*n} y2={h*n} className="gridline"/>)}{candles.map((c, i) => { const gain = c.close >= c.open; return <g key={c.time} className={gain ? "gain" : "loss"}><line x1={x(i)} x2={x(i)} y1={y(c.high)} y2={y(c.low)}/><rect x={x(i)-body/2} y={y(Math.max(c.open,c.close))} width={body} height={Math.max(1,y(Math.min(c.open,c.close))-y(Math.max(c.open,c.close)))}/></g> })}</svg>;
}

export default function Home() {
  const [tab, setTab] = useState<"overview"|"strategies"|"activity">("overview"); const [tokens, setTokens] = useState<Token[]>([]); const [symbol, setSymbol] = useState("BTCUSDT"); const [interval, setInterval] = useState("5m"); const [candles, setCandles] = useState<Candle[]>([]); const [assets, setAssets] = useState<Asset[]>([]); const [futures, setFutures] = useState<Asset[]>([]); const [accountNote, setAccountNote] = useState("Loading Toobit balances…"); const [connection, setConnection] = useState("Check connection"); const [bot, setBot] = useState<{running:boolean;message:string;positions:Array<{symbol:string;quantity:number}>}>({running:false,message:"Loading bot status…",positions:[]});
  useEffect(() => { fetch("/api/markets").then(r=>r.json()).then(d=>setTokens(d.tokens ?? [])); }, []);
  useEffect(() => { const load=()=>fetch(`/api/chart?symbol=${symbol}&interval=${interval}`).then(r=>r.json()).then(d=>setCandles(d.candles ?? [])); load(); const id=window.setInterval(load, interval === "1m" ? 10_000 : 30_000); return()=>window.clearInterval(id); }, [symbol,interval]);
  useEffect(() => { fetch("/api/account").then(r=>r.json()).then(d=>{setAssets(d.spot??[]);setFutures(d.futures??[]);setAccountNote(d.message);}); }, []);
  useEffect(() => { const load=()=>fetch("/api/bot").then(r=>r.json()).then(setBot); load(); const id=window.setInterval(load,5000); return()=>window.clearInterval(id); }, []);
  const selected = tokens.find(t=>t.symbol===symbol); const price = selected?.price ?? candles.at(-1)?.close ?? 0;
  async function test(){const r=await fetch("/api/connection",{method:"POST"});const d=await r.json();setConnection(d.message);if(d.ok) fetch("/api/account").then(x=>x.json()).then(x=>{setAssets(x.spot??[]);setFutures(x.futures??[]);setAccountNote(x.message);});}
  async function controlBot(action:"start"|"stop"){const r=await fetch("/api/bot",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});const d=await r.json();setBot(d.error?{...bot,message:d.error}:d);}
  return <main><header><div className="wordmark"><span>A</span>Axiom</div><nav>{(["overview","strategies","activity"] as const).map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</nav><button className="connect" onClick={test}>● {connection}</button></header>
    {tab==="overview" && <><section className="intro"><div><p className="kicker">SPOT WORKSPACE</p><h1>Trade with clarity.</h1><p>Market monitoring, account availability, and automation controls in one place.</p></div><button className="primary" onClick={()=>setTab("strategies")}>Configure strategy →</button></section>
    <section className="market-picker"><div><h2>Markets</h2><p>Select a spot pair to view. Prices refresh from Toobit.</p></div><div className="tokens">{tokens.map(t=><button key={t.symbol} onClick={()=>setSymbol(t.symbol)} className={symbol===t.symbol?"chosen":""}><b>{t.code}</b><span>{currency.format(t.price)}</span><em className={t.change>=0?"positive":"negative"}>{t.change>=0?"+":""}{t.change.toFixed(2)}%</em></button>)}</div></section>
    <section className="dashboard"><article className="chart-panel"><div className="panel-top"><div><p className="kicker">{symbol.replace("USDT"," / USDT")}</p><h2>{currency.format(price)}</h2></div><div className="intervals">{intervals.map(i=><button key={i} className={interval===i?"selected":""} onClick={()=>setInterval(i)}>{i}</button>)}</div></div><Candles candles={candles}/><p className="caption">Candles refresh automatically. Green means the period closed higher; red means it closed lower.</p></article><article className="asset-panel"><h2>Spot assets</h2><p className="caption">{accountNote}</p>{assets.length?<div className="assets">{assets.map(a=><div key={a.coin}><b>{a.coin}</b><span>{a.total.toLocaleString(undefined,{maximumFractionDigits:8})}</span><small>{a.free>0?`${a.free.toLocaleString(undefined,{maximumFractionDigits:8})} available to trade`:`${a.locked.toLocaleString(undefined,{maximumFractionDigits:8})} locked in orders`}</small></div>)}</div>:<div className="empty-state">No usable spot assets found.</div>}{futures.length>0&&<div className="elsewhere"><b>Funds in Futures</b><p>{futures.map(a=>`${a.coin} ${a.total}`).join(" · ")}</p><small>Transfer these funds to Spot in Toobit before this spot bot can use them.</small></div>}</article></section></>}
    {tab==="strategies" && <section className="page"><p className="kicker">AUTOMATION RULES</p><h1>Opening-range breakout &amp; retest</h1><div className="strategy"><div><span>01</span><h2>Opening range</h2><p>Record the first 5-minute high and low after UTC midnight.</p></div><div><span>02</span><h2>Entry rule</h2><p>Buy a 20-USDT position only after an upside breakout returns to, then holds, the range high.</p></div><div><span>03</span><h2>Exit &amp; protection</h2><p>Stop below the retest low. At +10%, activate a 3% trailing stop. Block new entries after a 3% realized daily bot loss.</p></div></div><div className="notice"><b>{bot.running?"Live worker running.":"Live worker stopped."}</b> {bot.message}<br/>{bot.positions.length?`Open bot position: ${bot.positions.map(p=>`${p.symbol} ${p.quantity}`).join(", ")}`:"No bot-managed position."}</div><div className="bot-actions"><button className="primary" onClick={()=>controlBot(bot.running?"stop":"start")}>{bot.running?"Stop bot":"Start live bot"}</button><small>Stopping the worker does not close an open Toobit position.</small></div></section>}
    {tab==="activity" && <section className="page"><p className="kicker">ACTIVITY</p><h1>Order history</h1><div className="empty-state">No live orders submitted. This view will list authenticated order updates once the execution worker is enabled.</div></section>}
  </main>;
}
