import './style.css';

// EarnResearch is intentionally client-side: provider calls go directly from this browser.
const SYSTEM_PROMPT = `You are an ethical money-making opportunities researcher. Your role is to suggest ONLY legitimate, legal, and ethical ways for people to earn money. Focus on real, actionable opportunities that a person with minimal resources can start today and a realistic first-dollar target. Be honest about uncertainty, difficulty, taxes, fees, competition, and hidden costs; never inflate earnings. Prefer well-known, verifiable platforms and say when legitimacy needs checking. Never suggest illegal activities (fraud, scams, hacking, drug sales, evasion), harmful or exploitative methods, deception, spam, pyramid schemes or MLM recruitment, gambling or betting strategies, cryptocurrency trading advice, get-rich-quick schemes, activities violating platform Terms of Service, or tax evasion. Only suggest methods that are legal in most jurisdictions. Return ONLY valid JSON with this shape: {"ideas":[{"title":"","category":"","description":"","effort":"Low|Medium|High","timeToFirstDollar":"","earnings":"","steps":[""],"tools":[""],"risk":"Low|Medium|High","legitimacy":"","budget":0,"quickWin":true}]} Do not make guarantees. If a request is unsafe, refuse it and offer a safe alternative.`;
const models = {gemini:['gemini-2.0-flash','gemini-1.5-flash'],openai:['gpt-4o-mini','gpt-3.5-turbo'],anthropic:['claude-3-5-haiku-latest','claude-3-haiku-20240307']};
const $ = (s) => document.querySelector(s); const $$ = (s) => [...document.querySelectorAll(s)];
let state = {ideas:[], saved:JSON.parse(localStorage.getItem('er_saved')||'[]'), earnings:JSON.parse(localStorage.getItem('er_earnings')||'[]'), category:'All', theme:localStorage.getItem('er_theme')||'light'};
const save = () => {localStorage.setItem('er_saved',JSON.stringify(state.saved));localStorage.setItem('er_earnings',JSON.stringify(state.earnings));};
const toast = (msg) => {const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3000)};
const show = (id,on=true) => {$(id).hidden=!on};
function setStatus(msg,error=false){const e=$('#status');e.hidden=!msg;e.textContent=msg;e.className='status'+(error?' error':'')}
function getProfile(){return {skills:$('#skills').value.trim(),time:$('#time').value,equipment:$('#equipment').value.trim(),region:$('#region').value.trim(),budget:$('#budget').value,quickWin:$('#quickWin').checked,zeroBudget:$('#zeroBudget').checked}}
function renderIdeas(){const grid=$('#ideaGrid');let list=state.ideas.filter(x=>state.category==='All'||x.category===state.category|| (state.category==='Quick wins'&&x.quickWin));if(!list.length){grid.innerHTML='<div class="empty-state">No ideas yet. Tell us what you can do, then generate your first research brief.</div>';return}grid.innerHTML=list.map((x,i)=>`<article class="idea-card"><div class="idea-top"><span class="tag">${esc(x.category||'Practical work')}</span><span class="tag">${esc(x.effort||'Medium')} effort</span></div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><div class="idea-meta"><span>FIRST DOLLAR<b>${esc(x.timeToFirstDollar||'Varies')}</b></span><span>REALISTIC RANGE<b>${esc(x.earnings||'Research needed')}</b></span></div><div class="card-actions"><button class="outline-btn small" data-view="${i}">View details</button><button class="primary-btn small" data-save="${i}">${state.saved.some(s=>s.title===x.title)?'✓ Saved':'Save idea'}</button></div></article>`).join('');$$('[data-view]').forEach(b=>b.onclick=()=>openDetail(list[+b.dataset.view]));$$('[data-save]').forEach(b=>b.onclick=()=>toggleSave(list[+b.dataset.save]));}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toggleSave(idea){const i=state.saved.findIndex(x=>x.title===idea.title);if(i>=0){state.saved.splice(i,1);toast('Removed from saved ideas')}else{state.saved.push({...idea,status:'Not started',notes:''});toast('Saved — your next small step is waiting')}save();renderIdeas();updateProgress()}
function openDetail(x){$('#detailContent').innerHTML=`<span class="eyebrow">${esc(x.category||'OPPORTUNITY')}</span><h2>${esc(x.title)}</h2><p>${esc(x.description)}</p><div class="idea-meta"><span>EFFORT<b>${esc(x.effort)}</b></span><span>FIRST DOLLAR<b>${esc(x.timeToFirstDollar)}</b></span><span>RISK<b>${esc(x.risk)}</b></span></div><h3 style="margin-top:22px">Getting started</h3><ol>${(x.steps||[]).map(s=>`<li>${esc(s)}</li>`).join('')}</ol><h3>Tools & resources</h3><p>${(x.tools||[]).map(esc).join(' · ')||'No special tools listed.'}</p><p><strong>Legitimacy notes:</strong> ${esc(x.legitimacy||'Verify platform terms, fees, reviews, and local requirements before committing time or money.')}</p><button class="primary-btn" id="planBtn">Generate a 7-day action plan</button><button class="outline-btn" id="reportBtn" style="margin-left:8px">Report concerning content</button>`;show('#detailModal');$('#planBtn').onclick=()=>followup(x,'Create a realistic 7-day action plan for this idea, with one small action per day.');$('#reportBtn').onclick=()=>{toast('Thanks — report noted locally. Please also verify the source independently.');localStorage.setItem('er_reported','true')}}
async function followup(idea,question){const answer=await callLLM(`Idea: ${JSON.stringify(idea)}\nUser request: ${question}\nReturn concise markdown.`);if(answer){$('#detailContent').insertAdjacentHTML('beforeend',`<div class="status" style="margin-top:18px"><strong>Action plan</strong><br>${esc(answer).replace(/\n/g,'<br>')}</div>`)}}
async function callLLM(user){const provider=localStorage.getItem('er_provider');const key=await decryptKey();if(!provider||!key){show('#settingsModal');setStatus('Connect an LLM provider in Settings to generate personalized research.',true);return null}if(Date.now()-(+localStorage.getItem('er_lastCall')||0)<4000){setStatus('Please wait a few seconds between research requests.',true);return null}localStorage.setItem('er_lastCall',Date.now());let url,headers={'Content-Type':'application/json'},body;if(provider==='gemini'){url=`https://generativelanguage.googleapis.com/v1beta/models/${localStorage.getItem('er_model')}:generateContent?key=${encodeURIComponent(key)}`;body={systemInstruction:{parts:[{text:SYSTEM_PROMPT}]},contents:[{role:'user',parts:[{text:user}]}],generationConfig:{temperature:.35,responseMimeType:'application/json'}}}else if(provider==='openai'){url='https://api.openai.com/v1/chat/completions';headers.Authorization=`Bearer ${key}`;body={model:localStorage.getItem('er_model'),messages:[{role:'system',content:SYSTEM_PROMPT},{role:'user',content:user}],temperature:.35,response_format:{type:'json_object'}}}else{url='https://api.anthropic.com/v1/messages';headers['x-api-key']=key;headers['anthropic-version']='2023-06-01';body={model:localStorage.getItem('er_model'),system:SYSTEM_PROMPT,max_tokens:3000,messages:[{role:'user',content:user}]}}try{const r=await fetch(url,{method:'POST',headers,body:JSON.stringify(body)});if(r.status===429)throw Error('Rate limited by provider. Please wait and try again.');if(!r.ok)throw Error(`Provider returned ${r.status}. Check the key, model, and quota.`);const d=await r.json();let text=provider==='gemini'?d.candidates?.[0]?.content?.parts?.[0]?.text:provider==='openai'?d.choices?.[0]?.message?.content:d.content?.[0]?.text;if(!text)throw Error('The provider returned an unexpected response.');return text.replace(/^```json\s*|```$/g,'').trim()}catch(e){setStatus(e.message+' No data was saved.',true);return null}}
async function generate(prompt=''){setStatus('Researching carefully…');$('#ideaGrid').innerHTML='<div class="skeleton"></div><div class="skeleton"></div>';const p=getProfile();const raw=await callLLM(`User profile: ${JSON.stringify(p)}\nRequest: ${prompt||$('#query').value||'Give me 6 varied, practical ways to earn a first $1, respecting the profile.'}\nPrioritize no-cost and quick-start ideas where selected. Never promise income.`);if(!raw)return;try{const d=JSON.parse(raw);state.ideas=(d.ideas||[]).map(x=>({...x,quickWin:Boolean(x.quickWin)}));renderIdeas();setStatus(`${state.ideas.length} ideas researched. Verify details before acting.`)}catch(e){setStatus('The response was malformed. Try again or choose another model.',true);renderIdeas()}}
async function decryptKey(){const packed=localStorage.getItem('er_key');const pass=$('#vaultPass')?.value||sessionStorage.getItem('er_pass');if(!packed||!pass)return null;try{const [iv,salt,data]=packed.split('.').map(x=>Uint8Array.from(atob(x),c=>c.charCodeAt(0)));const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']);const aes=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:100000,hash:'SHA-256'},k,{name:'AES-GCM',length:256},false,['decrypt']);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},aes,data);sessionStorage.setItem('er_pass',pass);return new TextDecoder().decode(plain)}catch{return null}}
async function encryptKey(key,pass){const enc=new TextEncoder(),iv=crypto.getRandomValues(new Uint8Array(12)),salt=crypto.getRandomValues(new Uint8Array(16));const base=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']);const aes=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:100000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt']);const out=await crypto.subtle.encrypt({name:'AES-GCM',iv},aes,enc.encode(key));const b=a=>btoa(String.fromCharCode(...a));return [b(iv),b(salt),b(new Uint8Array(out))].join('.')}
function updateProgress(){const done=state.saved.filter(x=>x.status==='Done').length;$('#progressCount').textContent=done;$('#pursuingCount').textContent=`${state.saved.length} idea${state.saved.length===1?'':'s'} in motion`}
function renderEarnings(){$('#earningsList').innerHTML=state.earnings.length?state.earnings.map(x=>`<p>+ <strong>$${esc(x.amount)}</strong> · ${esc(x.note)} <span class="muted">${esc(x.date)}</span></p>`).join(''):'No earnings logged yet.'}
function updateModels(){const p=$('#provider').value;$('#model').innerHTML=models[p].map(x=>`<option>${x}</option>`).join('')}
$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal-backdrop').hidden=true);$('#settingsBtn').onclick=$('#settingsInline').onclick=()=>show('#settingsModal');$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';document.body.classList.toggle('dark',state.theme==='dark');localStorage.setItem('er_theme',state.theme)};if(state.theme==='dark')document.body.classList.add('dark');$('#provider').onchange=updateModels;updateModels();$('#generateBtn').onclick=()=>generate();$('#startBtn').onclick=()=>{$('#query').focus();window.scrollTo({top:450,behavior:'smooth'})};$('#sampleBtn').onclick=()=>{$('#query').value='I need $10 this weekend using writing and a laptop';generate()};$('#trendingBtn').onclick=()=>generate('Research currently relevant opportunities, but label any time-sensitive claims and do not pretend to have live browsing.');$('#dismissNotice').onclick=e=>e.currentTarget.parentElement.remove();$('#saveSettings').onclick=async()=>{const key=$('#apiKey').value.trim(),pass=$('#vaultPass').value;if(!key||pass.length<8){$('#connectionStatus').hidden=false;$('#connectionStatus').className='status error';$('#connectionStatus').textContent='Enter an API key and a vault passphrase of at least 8 characters.';return}localStorage.setItem('er_key',await encryptKey(key,pass));localStorage.setItem('er_provider',$('#provider').value);localStorage.setItem('er_model',$('#model').value);sessionStorage.setItem('er_pass',pass);$('#connectionStatus').hidden=false;$('#connectionStatus').textContent='Encrypted locally. Connection will be tested with your next research request.';toast('Settings saved securely')};$('#addEarningBtn').onclick=()=>{const amount=prompt('Amount earned (USD):');if(!amount||isNaN(+amount))return;const note=prompt('What was it for?')||'Unspecified';state.earnings.unshift({amount:(+amount).toFixed(2),note,date:new Date().toLocaleDateString()});save();renderEarnings();toast('Earning logged')};$('#exportBtn').onclick=()=>{const data=JSON.stringify({saved:state.saved,earnings:state.earnings},null,2),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'application/json'}));a.download='earnresearch-export.json';a.click()};$('#clearDataBtn').onclick=()=>{if(confirm('Clear saved ideas, earnings, encrypted key, and preferences?')){localStorage.clear();sessionStorage.clear();location.reload()}};$$('#categoryTabs button').forEach(b=>b.onclick=()=>{$$('#categoryTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.category=b.dataset.cat;renderIdeas()});renderIdeas();renderEarnings();updateProgress();
